services:
    # nginx
    web:
        image: nginx:latest
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./www/public:/var/www/html/public:ro
        ports:
            - "80:80"
        depends_on:
            - app
    # php
    app:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile.dev
        env_file:
            - www/.env
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            APP_LOCALE: ${APP_LOCALE}
            APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE}
            APP_FAKER_LOCALE: ${APP_FAKER_LOCALE}
            APP_MAINTENANCE_DRIVER: ${APP_MAINTENANCE_DRIVER}
            # APP_MAINTENANCE_STORE: ${APP_MAINTENANCE_STORE}

            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

            GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

            REDIS_CLIENT: ${REDIS_CLIENT}
            REDIS_HOST: cache

            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_SCHEME: ${MAIL_SCHEME}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}

            XDEBUG_MODE: ${XDEBUG_MODE:-develop,debug,coverage}
        volumes:
            - ./www:/var/www/html
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway
        depends_on:
            - db
            - cache
    node:
        image: node:22-alpine
        working_dir: /var/www/html
        env_file:
            - www/.env
        volumes:
            - ./www:/var/www/html
        command: sh -c "npm install && npm run dev"
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
            - "./docker/mysql/init:/docker-entrypoint-initdb.d"
        restart: always
        env_file:
            - www/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    # redis
    cache:
        image: redis:latest
        volumes:
            - redisdata:/data

volumes:
    mysqldata:
        driver: local
    redisdata:
        driver: local
